Upstream merge fixes
Consensys-Incorporated/quorum pull request #1273
Opened 2021-10-28 15:59 UTC by chris-j-h

Fixes relating to recent upstream geth merges.  

* https://github.com/ethereum/go-ethereum/pull/21509
    * The upstream merge introduced `ActivePrecompiles()` however there is a typo causing tests added in this PR to fail.  This bug was fixed in upstream 1.10.2 - the content of that fix has been included in this change.  To simplify future merges the content of the commit has been copied instead of cherry-picking the commit.
    * The Quorum Privacy Precompile address has been added to `ActivePrecompiles()` list. This is currently only used for the experimental YoloV2 EIP 2929 (where all active precompiles for the current block height must be known) so not critical but worth fixing ahead of the concrete release that will be pulled in from a future upstream geth merge.

2021-10-28 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/ConsenSys/quorum?pullRequest=1273) <br/>All committers have signed the CLA.

2021-10-28 16:58 UTC, Krish1979 submitted a review, later dismissed
LGTM

2021-10-29 10:00 UTC, baptiste-b-pegasys submitted a review, later dismissed

2021-11-01 09:51 UTC, antonydenyer requested changes
I don't think trying to cherry-pick changes from prior releases makes sense. At this point in time, the master branch is working from geth upstream v1.9.25.

2021-11-01 10:10 UTC, chris-j-h commented
@antonydenyer would you rather getting rid of the upstream cherry-pick and making the bug fix as part of commit a8338d8?

2021-11-01 10:12 UTC, antonydenyer commented
:+1: Yeah let's do that for now.

2021-11-01 10:26 UTC, antonydenyer approved these changes

2021-11-01 10:43 UTC, Krish1979 approved these changes
LGTM

2021-11-01 12:52 UTC, baptiste-b-pegasys approved these changes

2021-11-02 09:02 UTC, merged