validation rewards
Consensys-Incorporated/quorum pull request #1502
Opened 2022-09-12 10:37 UTC by baptiste-b-pegasys

Configure a way to gets rewards when there is a block validation

2022-09-12 11:30 UTC, baptiste-b-pegasys commented on consensus/istanbul/qbft/engine/engine.go
> +	log.Info("finalize", "coinbase", header.Coinbase)
```suggestion
```

2022-09-12 11:31 UTC, baptiste-b-pegasys commented on consensus/istanbul/qbft/engine/engine.go
> +	log.Info("add balance", "coinbase", headerCoinbase, "reward", reward)
```suggestion
```
no uncle and remove added log

2022-09-27 14:52 UTC, antonydenyer requested changes

2022-09-27 14:52 UTC, antonydenyer commented on consensus/istanbul/qbft/engine/engine.go
> +		log.Warn("beneficiary mode not known", "mode", *cfg.BeneficiaryMode)
This will be very spammy - can we do something with validation at startup rather than on every call to `accumulateRewards`

2022-09-29 13:03 UTC, achraf17 approved these changes
LGTM

2022-09-30 08:27 UTC, antonydenyer approved these changes

2022-09-30 10:37 UTC, antonydenyer commented
Can we change `case "besu":` to `case "single"` or something like that?

2022-10-03 08:33 UTC, merged