extension: expose generation of management contract uuid to allow external signing of approval request
Consensys-Incorporated/quorum pull request #1613
Opened 2023-02-22 06:49 UTC by rodion-lim-partior

This PR introduces the following changes to the extension API:

1. Expose the generation of management contract uuid to be used in a separate call to `doVote` function by the approver

This allows the subsequent transaction for approval of contract state extension to be submitted as a rawPrivateTransaction and signed externally.

2023-02-22 06:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ConsenSys/quorum?pullRequest=1613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ConsenSys/quorum?pullRequest=1613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ConsenSys/quorum?pullRequest=1613) it.</sub>

2023-03-07 10:20 UTC, antonydenyer commented
Thanks for the PR. I'm a little reticent to merge this, you can call the contract directly using standard tooling. I think there are some endpoints that have been added that are in the same situation, but given they are already in the product we're not going to be removing them. 

Could you provide further details as to why this is needed and something that can not be done without this change?

2023-03-10 13:38 UTC, rodion-lim-partior commented
Hi, one thing I noticed was having to get the `uuid` to be an encoded hash of the management contract stored within the "standard" database of Tessera before contract state extension can be picked up for the state dump upon approval. Correct me if I'm wrong, but getting the uuid stored requires hitting the Q2T `send` endpoint. Without exposing this in the RPC calls, our external clients need to hit the Q2T endpoint.

I agree with you that contract state extension approval with an external signer can be done without this change, but I'm not too sure if having an external client call the Q2T endpoint is a good design choice, and whether there are any other ways around this. Thanks.

2023-03-16 09:17 UTC, antonydenyer requested changes
Fair enough - it's one of things that you could do without changes to quorum. But perhaps you're right, the correct place to do it is here. 

Can you add an acceptance test in https://github.com/ConsenSys/quorum-acceptance-tests ? Then we can get this merged.

2023-03-16 10:05 UTC, rodion-lim-partior commented
Got it, thanks for the clarification. I'll add the acceptance test in and update again.

2023-03-18 09:42 UTC, Krish1979 commented
contract extension was always built like as an admin only feature i.e., to work with a node managed account and that the sender and receiver nodes are managing the extension and not by some externally owned account operating on the receiver node. The PR relaxes the rule a bit and there are certain processes for which an account needs to be maintained on the node.

2023-03-20 06:17 UTC, rodion-lim-partior commented
Hi @Krish1979, reason for raising this PR is to enable parties to use the contract state extension approval feature without storing any local account within the node (using pre-signed raw txn instead), which could increase the attack surface if the RPC endpoint gets compromised.

2023-03-20 11:14 UTC, Krish1979 commented
as long as you have local account's privacy key stored in a vault (integrated) and using Quorum or Clef to sign the account, you are not elevating the risk in anyway.

2023-03-20 16:14 UTC, krishnan-narayanan-partior commented
Hi @Krish1979, use of geth for account signing is ruled out as this will be deprecated in future releases. Clef only supports hashicorp vault (through plugin) and there is no support for HSMs based signing. This PR will allow wider options for account signing during the contract extension approval process.

2023-03-20 16:45 UTC, Krish1979 commented
There is no plan to deprecate account signing in Quorum. We may still retain that, also you could use https://github.com/ConsenSys/quorum-key-manager for wider option.

2023-03-20 17:36 UTC, krishnan-narayanan-partior commented
@Krish1979 Thanks for sharing the link, the quorum key manager mainly supports KV store and doesn't support HSMs which are FIPS-140 Level 2-3 standard. Can the account signing be relaxed instead of mandating use of some plugins like clef and QKM with limited capabilities?

You mentioned the below, can you please let us know which processes requires an account to be maintained on the node?

> The PR relaxes the rule a bit and there are certain processes for which an account needs to be maintained on the node

2023-03-24 09:14 UTC, rodion-lim-partior commented
@antonydenyer, I raised a [PR](https://github.com/ConsenSys/quorum-acceptance-tests/pull/210) to add an acceptance test for the new feature introduced.

2023-03-24 10:36 UTC, antonydenyer commented
I think the main outstanding question is how much risk does exposing the approval uuid add?

2023-03-24 11:44 UTC, rodion-lim-partior commented
Hi @antonydenyer, even without exposing the approval uuid, recipients are able to approve with an external signer (using a non admin private/public key pair) if they call the q2t endpoint directly, before hitting the management contract directly. In terms of outstanding risk, it would be pretty similar for both cases. Also, this reduces the need for participants to maintain unlocked accounts within the rpc node just for the purposes of approving contract state extensions.

2023-03-29 11:01 UTC, Krish1979 commented
@rodion-lim-partior  - The contract extension method was always designed to be node level operation ("using node managed account") and not account level operation. The contract extension initiation still has to be triggered by a node managed account. Could you please confirm if you intend to allow initiating contract extension from external owned accounts as well ?

2023-03-29 11:12 UTC, rodion-lim-partior commented
@Krish1979, there's no intention to allow initiating contract state extension from externally owned accounts, only the approval of contract state extension. Initiation of contract state extension still requires node managed accounts even after this PR.

2023-03-29 11:16 UTC, Krish1979 approved these changes

2023-03-29 11:59 UTC, merged