Update the key usage on Tessera transaction flow
Consensys-Incorporated/quorum pull request #782
Opened 2019-07-22 14:26 UTC by Krish1979

Updated the use of master and symmetric key.

2019-07-22 15:09 UTC, prd-fox requested changes

2019-07-22 15:09 UTC, prd-fox commented on docs/Privacy/Tessera/How Tessera Works.md
> +    1. encrypting the Transaction payload and Nonce with RMK from a.
```suggestion
    1. encrypting the transaction payload with the nonce with RMK from a.
```

2019-07-22 15:09 UTC, prd-fox commented on docs/Privacy/Tessera/How Tessera Works.md
> +    1. iterating through the list of Transaction recipients, in this case Parties A and B, and encrypting the RMK from a. with the shared key of Party A's private key and Party B's public key (PGP en
```suggestion
    1. iterating through the list of transaction recipients, in this case parties A and B, and encrypting the RMK from a. with the shared key of Party A's private key and Party B's public key, along with another randomly generated nonce
```

2019-07-23 08:11 UTC, prd-fox submitted a review, later dismissed

2019-07-23 15:19 UTC, fixanoid submitted a review, later dismissed

2019-08-07 20:40 UTC, jpmsam approved these changes

2019-08-07 20:52 UTC, merged