Documentation for Tessera AWS Secrets Manager implementation
Consensys-Incorporated/quorum pull request #919
Opened 2019-12-20 08:18 UTC by Emi14

2019-12-23 12:27 UTC, Krish1979 submitted a review, later dismissed

2020-01-09 17:44 UTC, chris-j-h requested changes
Please make the suggested changes so that the docs reflect our updated config

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +    "awsKeyVaultConfig":{
```suggestion
    "keyVaultConfig": {
        "keyVaultConfigType": "AWS",
        "properties": {
            "endpoint": "Url"
        }
    },
```

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +          "endpoint": "Url"
```suggestion
```

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +        "awsKeyVaultConfig":{
```suggestion
        "keyVaultConfig": {
            "keyVaultConfigType": "AWS",
            "properties": {
                "endpoint": "https://secretsmanager.us-west-2.amazonaws.com"
            }
        },
```

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +            "endpoint": "https://secretsmanager.us-west-2.amazonaws.com"
```suggestion
```

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +        },
```suggestion
```

2020-01-09 17:44 UTC, chris-j-h commented on docs/Privacy/Tessera/Configuration/Keys.md
> +      }
```suggestion
```

2020-01-10 07:09 UTC, Emi14 commented
@chris-j-h could you please take another look?

2020-01-10 09:24 UTC, chris-j-h submitted a review, later dismissed
looks good

2020-01-10 09:27 UTC, Krish1979 submitted a review, later dismissed

2020-01-10 14:06 UTC, jpmsam commented
Thank you @Emi14 and Ionut. We'll merge it after the Tessera release.

2020-02-10 15:35 UTC, Krish1979 approved these changes

2020-02-10 16:12 UTC, merged